//opencv
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
//C
#include <stdio.h>
#include <stdlib.h>
//C++
#include <iostream>
#include <sstream>
using namespace cv;
using namespace std;

class BallLoc
{
    int _x, _y, _age;
public:
    BallLoc(int x, int y) {
      _x = x;
      _y = y;
    }

    int getX() { return _x; }
    int getY() { return _y; }
    int getAge() { return _age; }

    void incFrameAge()
    {
        _age = _age + 1;
    }
};

// Global variables
Mat frame; //current frame
Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
Mat secondfgMaskMOG2;
Mat ballPathFrame; //this is your image to draw, don't forget to load it
Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
Ptr<BackgroundSubtractor> secondPMOG2;

// Initial Ball Location
int ballX = 1000;
int ballY = 770;

// Total Search Space for ball
int totalSpaceLB = 30;
int totalSpaceRB = 1700; // Width - totalSpaceLB
int totalSpaceTB = 100;
int totalSpaceBB = 1500; // Height - totalSpaceTB

// Strike Zone/Path Zone
int initSzWidth = 300;
int initSzHeight = 400;

// Start zone
int leftBorder = ballX - (initSzWidth / 2);
int rightBorder = ballX + (initSzWidth / 2);
int bottomBorder = ballY - (initSzHeight / 4) * 3;
int topBorder = ballY + (initSzHeight / 4);

// Distance Pixel can be from previous pixel
const int PER_FRAME_PIXEL_DISTANCE = 20;

// Frame Tracing Buffer
const int FRAME_WINDOW = 4;
std::vector<Mat> prevFrameBuffer(FRAME_WINDOW);
int prevFrameBufferCircIndex = 0; //Circular buffer index for prevFrames

// List of valid vectors
std::vector<std::vector<BallLoc> > validPaths;

double fgThreshold = 0.1;
double secondFgThreshold = 0.5;
char keyboard; //input from keyboard
void help();
void processVideo(char* videoFilename);
void processImages(char* firstFrameFilename);
void help(){
    cout
    << "--------------------------------------------------------------------------" << endl
    << "This program shows how to use background subtraction methods provided by "  << endl
    << " OpenCV. You can process both videos (-vid) and images (-img)."             << endl
                                                                                    << endl
    << "Usage:"                                                                     << endl
    << "./bg_sub {-vid <video filename>|-img <image filename>}"                     << endl
    << "for example: ./bg_sub -vid video.avi 0.05"                                  << endl
    << "or: ./bg_sub -img /data/images/1.png"                                       << endl
    << "--------------------------------------------------------------------------" << endl
    << endl;
}

int previousBufferHeadIndex(){
  prevFrameBufferCircIndex  = (prevFrameBufferCircIndex <= 0) ? FRAME_WINDOW - 1 : prevFrameBufferCircIndex  - 1;
}

// what to set the next head to..
int nextBufferHeadIndex(){
  (prevFrameBufferCircIndex + 1) % FRAME_WINDOW;
}

int incBufferHeadIndex(){
   prevFrameBufferCircIndex = nextBufferHeadIndex();
}



Scalar intensity;
// For the frame, check if there exists a pixel within the path
// baseFactor: base is (baseFactor * PER_FRAME_PIXEL_DISTANCE)
//             e.g. for a triangle with base half the height, set to
bool hasPathPixel(int x, int y, int baseFactor, Mat& curr){
  int i,j;
  int minX, maxX;
  int pixelVal;
  // From top to bottom
  for(j = y + PER_FRAME_PIXEL_DISTANCE; j >= y; --j){
    //Left to right, shrinking as it goes
    minX = x - (int)(PER_FRAME_PIXEL_DISTANCE * baseFactor) + (j - y);
    //cout << "minX: " << minX << endl;
    maxX = x + (int)(PER_FRAME_PIXEL_DISTANCE * baseFactor) - (j - y);
    //cout << "maxX: " << maxX << endl;
    for(i = minX; i < maxX; ++i){
      intensity = curr.at<uchar>(i, j);
      pixelVal = intensity.val[0];

      //cout << intensity.val[0];
      // if(pixelVal !=0){
      //   cout << pixelVal << endl;
      // }
      if(pixelVal == 255 || pixelVal == 127){
         return true;
      }
    }
  }
  return false;
}

// Go backward looking for indexes
int nextPrevBufferIndex(int framesPrior, int currIndex){
  return (currIndex - framesPrior < 0) ? FRAME_WINDOW - framesPrior : currIndex - framesPrior;
}

//Checks if the pixel is a valid pixel by looking at the previous frames
//and reaching further out as the frames go.
//Mat iFrame; // TODO should be pointer maybe
bool atLeastOneFrameSatisfies(int x, int y, Mat& curr){
  int i;
  int currBuffIndex = prevFrameBufferCircIndex;

  Mat iFrame;
  for(i = 0; i < FRAME_WINDOW - 1; i++){
    currBuffIndex = nextPrevBufferIndex(i, currBuffIndex);
    iFrame = prevFrameBuffer[currBuffIndex];

    if(hasPathPixel(x, y + (PER_FRAME_PIXEL_DISTANCE * i), 1, iFrame)){
      return true;
    }
    currBuffIndex = previousBufferHeadIndex();
  }
  return false;
}


void nextFrame(Mat& curr){
  //Loop through each pixel in the "Valid frame"
  // Valid Frame upper bound = where vector cannot "begin"
  // Valid Frame lower bound = user defined ball location + Splash Zone height

}


int main(int argc, char* argv[]) {
    //print help information
    help();
    //check for the input parameter correctness
    if(argc != 4) {
        cerr <<"Incorret input list" << endl;
        cerr <<"exiting..." << endl;
        return EXIT_FAILURE;
    }
    //create GUI windows
    //namedWindow("Ball path");
    //namedWindow("Frame");
    namedWindow("FG Mask MOG 2", WINDOW_NORMAL);
    //namedWindow("Prev validated", WINDOW_NORMAL);

    //namedWindow("Second FG Mask MOG 2");
    //create Background Subtractor objects
    pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach
    //secondPMOG2 = createBackgroundSubtractorMOG2();
    if(strcmp(argv[1], "-vid") == 0) {
        //input data coming from a video
        fgThreshold = atof(argv[3]);
        processVideo(argv[2]);
    }
    else if(strcmp(argv[1], "-img") == 0) {
        //input data coming from a sequence of images
        //processImages(argv[2]);
    }
    else {
        //error in reading input parameters
        cerr <<"Please, check the input parameters." << endl;
        cerr <<"Exiting..." << endl;
        return EXIT_FAILURE;
    }
    //destroy GUI windows
    destroyAllWindows();
    return EXIT_SUCCESS;
}

void processVideo(char* videoFilename) {
    //create the capture object
    VideoCapture capture(videoFilename);
    if(!capture.isOpened()){
        //error in opening the video input
        cerr << "Unable to open video file: " << videoFilename << endl;
        exit(EXIT_FAILURE);
    }
    //read input data. ESC or 'q' for quitting
    keyboard = 0;

    // path variables; Write the ball path
    std::vector<cv::Point> ballLocations; //fill this vector with points, they should be ordered
    int pathX = 200;
    int pathY = 50;
    cv::Scalar color(0, 0, 255); //red

    for(int i = 10; i < 1000 - 1; ++i)
    {
        Point pt;
        pt.x = i;//pathX;
        pt.y = i;
        ballLocations.push_back(pt);
    }

    while( keyboard != 'q' && keyboard != 27 ){
        //read the current frame
        if(!capture.read(frame)) {
            cerr << "Unable to read next frame." << endl;
            cerr << "Exiting..." << endl;
            exit(EXIT_FAILURE);
        }
        //update the background model
        pMOG2->apply(frame, fgMaskMOG2, fgThreshold);
        //secondPMOG2->apply(fgMaskMOG2, secondfgMaskMOG2, secondFgThreshold); // For fun...

        //get the frame number and write it on the current frame
        stringstream ss;
        rectangle(fgMaskMOG2, cv::Point(leftBorder, bottomBorder), cv::Point(rightBorder, topBorder),
                  cv::Scalar(255,255,255), 1);
        ss << capture.get(CAP_PROP_POS_FRAMES);
        string frameNumberString = ss.str();
        putText(frame, frameNumberString.c_str(), cv::Point(15, 15),
                FONT_HERSHEY_SIMPLEX, 0.5 , cv::Scalar(0,0,0));

        ballPathFrame = frame;
        // paint the ball path
        //printf("%d\n", ballLocations.size());
        for(int i = 0; i < ballLocations.size() - 1; ++i)
        {
           cv::line(ballPathFrame, ballLocations[i], ballLocations[i+1], color);
        }

        Mat frame;
        //frame = ScanImageAndReduceC(fgMaskMOG2);
        bool found;
        found = hasPathPixel(500, 800, 1, fgMaskMOG2);
        cout << "Found: " << found << endl;

        //show the current frame and the fg masks
        //imshow("Ball path", ballPathFrame);
        //imshow("Frame", frame);
        imshow("FG Mask MOG 2", fgMaskMOG2);
        //imshow("Prev validated", frame);

        //get the input from the keyboard
        keyboard = (char)waitKey(1);

        // Iterate the zone..
        bottomBorder = bottomBorder - 3;
        topBorder = topBorder - 3;
    }
    //delete capture object
    capture.release();
}
